version: "3.7"

services:

  db:
    container_name: postgres
    image: postgres:15.2
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    container_name: redis
    image: redis:5.0
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - backend

  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
    networks:
      - backend

#  backend:
#    container_name: backend
#    build:
#      context: .
#      dockerfile: ./backend/Dockerfile
#    restart: always
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./backend:/app

volumes:
  postgres_data:
  redis_data:
  redis-insight:

networks:
  backend:
